config/routes.rb
Datasheets::Application.routes.draw do
  resources :small_generators
  root :to => 'small_generators#index'
end

app/models/small_generator.rb
class SmallGenerator
  include Mongoid::Document

  field :model, type: String
  field :kva_max, type: Float
  field :kva_cont, type: Float
  field :kw_max, type: Float
  field :kw_cont, type: Float
  field :start, type: String
  field :dimenzije, type: String
  field :masa, type: Integer
  field :motor_proizvodjac, type: String
  field :motor_tip, type: String
  field :motor_hp, type: Float
  field :motor_rpm, type: Integer
  field :motor_cilindri, type: Integer
  field :motor_cm3, type: Integer
  field :motor_gorivo, type: String
  field :motor_hladjenje, type: String
  field :motor_potrosnja_75, type: Float
  field :motor_rezervoar, type: Float
  field :autonomija, type: Float
  field :nivo_buke, type: Integer
  field :generator_proizvodjac, type: String
  field :generator_tip, type: String
  field :napon, type: String
  field :frekvencija, type: Integer
  field :panel, type: String

  # Validations
  validates_presence_of :model, :kva_max, :kva_cont, :kw_max, :kw_cont,
                        :start, :motor_proizvodjac, :motor_tip, :motor_rpm,
                        :motor_cilindri, :motor_gorivo, :motor_hladjenje,
                        :generator_proizvodjac, :napon, :frekvencija, :panel

  validates :kva_max,             numericality: { greater_than: 0 }
  validates :kva_cont,            numericality: { greater_than: 0 }
  validates :kw_max,              numericality: { greater_than: 0 }
  validates :kw_cont,             numericality: { greater_than: 0 }
  validates :start,               format: { with: /^[R|E]$/ }
  validates :dimenzije,           format: { with: /^\d+x\d+x\d+$/ }, allow_blank: true
  validates :masa,                numericality: { greater_than: 0 }
  validates :motor_hp,            numericality: { greater_than: 0 }, allow_blank: true
  validates :motor_rpm,           numericality: { greater_than: 0 }
  validates :motor_cilindri,      numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 4 }
  validates :motor_cm3,           numericality: { greater_than: 0 }, allow_blank: true
  validates :motor_potrosnja_75,  numericality: { greater_than: 0 }, allow_blank: true
  validates :motor_rezervoar,     numericality: { greater_than: 0 }, allow_blank: true
  validates :autonomija,          numericality: { greater_than: 0 }, allow_blank: true
  validates :nivo_buke,           numericality: { greater_than: 0 }, allow_blank: true
  validates :frekvencija,         numericality: { greater_than: 0 }

  #default scope to sort by power
  default_scope order_by(kva_max: "asc")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/small_generators_controller.rb
class SmallGeneratorsController < ApplicationController
  # GET /small_generators
  # GET /small_generators.json
  def index
    @small_generators = SmallGenerator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @small_generators }
    end
  end

  # GET /small_generators/1
  # GET /small_generators/1.json
  def show
    @small_generator = SmallGenerator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @small_generator }
      format.pdf do
        pdf = SmallGeneratorsPdf.new @small_generator, view_context
        send_data pdf.render,
                  type: "application/pdf",
                  disposition: "inline",
                  filename: "#{@small_generator.model}.pdf"
      end
    end
  end

  # GET /small_generators/new
  # GET /small_generators/new.json
  def new
    @small_generator = SmallGenerator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @small_generator }
    end
  end

  # GET /small_generators/1/edit
  def edit
    @small_generator = SmallGenerator.find(params[:id])
  end

  # POST /small_generators
  # POST /small_generators.json
  def create
    @small_generator = SmallGenerator.new(params[:small_generator])

    respond_to do |format|
      if @small_generator.save
        format.html { redirect_to @small_generator, notice: 'Small generator was successfully created.' }
        format.json { render json: @small_generator, status: :created, location: @small_generator }
      else
        format.html { render action: "new" }
        format.json { render json: @small_generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /small_generators/1
  # PUT /small_generators/1.json
  def update
    @small_generator = SmallGenerator.find(params[:id])

    respond_to do |format|
      if @small_generator.update_attributes(params[:small_generator])
        format.html { redirect_to @small_generator, notice: 'Small generator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @small_generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /small_generators/1
  # DELETE /small_generators/1.json
  def destroy
    @small_generator = SmallGenerator.find(params[:id])
    @small_generator.destroy

    respond_to do |format|
      format.html { redirect_to small_generators_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/small_generators_helper.rb
module SmallGeneratorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datasheets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/">Datasheets</a>
      <ul class="nav">
        <li><%= link_to "Početna", root_path %></li>
        <li><%= link_to "Mali agregati", small_generators_path %></li>
        <li><a href="#">Industrijski agregati</a></li>
      </ul>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/small_generators/_form.html.erb
<%= form_for(@small_generator, html: {class: "form-horizontal"}) do |f| %>
  <% if @small_generator.errors.any? %>
    <div class="alert alert-error fade in">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Molimo Vas ispravite greške ispod</strong>
      <ul>
      <% @small_generator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :model, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :model, placeholder: "BS3001R" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kva_max, "Stand by snaga", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :kva_max, placeholder: "3" %>
        <span class="add-on">kVA</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kva_cont, "Prime snaga", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :kva_cont, placeholder: "2.8" %>
        <span class="add-on">kVA</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kw_max, "Stand by snaga", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :kw_max, placeholder: "3" %>
        <span class="add-on">kW</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kw_cont, "Prime snaga", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :kw_cont, placeholder: "2.8" %>
        <span class="add-on">kW</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start, class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :start, placeholder: "R" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dimenzije, class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :dimenzije, placeholder: "800x500x500" %>
        <span class="add-on">mm</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :masa, class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.number_field :masa, placeholder: "35" %>
        <span class="add-on">kg</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_proizvodjac, "Proizvođač motora", class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :motor_proizvodjac, placeholder: "Briggs&Stratton" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_tip, "Tip motora", class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :motor_tip, placeholder: "Vanguard 13H1" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_hp, "Snaga motora", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :motor_hp, placeholder: "6.5" %>
        <span class="add-on">hp</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_rpm, "Broj obrtaja", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.number_field :motor_rpm, placeholder: "3000" %>
        <span class="add-on">rpm</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_cilindri, "Broj cilindara", class: "control-label"  %>
    <div class="controls">
      <%= f.number_field :motor_cilindri, placeholder: "1" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_cm3, "Zapremina motora", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.number_field :motor_cm3, placeholder: "205" %>
        <span class="add-on">cm<sup>3</sup></span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_gorivo, "Pogonsko gorivo", class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :motor_gorivo, placeholder: "benzin" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_hladjenje, "Vrsta hlađenja", class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :motor_hladjenje, placeholder: "vazdušno" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_potrosnja_75, "Potrošnja na 75%", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :motor_potrosnja_75, placeholder: "1.5" %>
        <span class="add-on">l/h</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :motor_rezervoar, "Zapremina rezervoara", class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :motor_rezervoar, placeholder: "3.8" %>
        <span class="add-on">l</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :autonomija, class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :autonomija, placeholder: "2.5" %>
        <span class="add-on">h</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nivo_buke, class: "control-label"  %>
    <div class="controls">
      <%= f.number_field :nivo_buke, placeholder: "96" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :generator_proizvodjac, "Proizvođač generatora", class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :generator_proizvodjac, placeholder: "Linz" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :generator_tip, "Tip generatora", class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :generator_tip, placeholder: "SP10SD" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :napon, class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :napon, placeholder: "230" %>
        <span class="add-on">V</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :frekvencija, class: "control-label"  %>
    <div class="controls">
      <div class="input-append">
        <%= f.number_field :frekvencija, placeholder: "50" %>
        <span class="add-on">Hz</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :panel, class: "control-label"  %>
    <div class="controls">
      <%= f.text_field :panel, placeholder: "Panel 1" %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <div class="actions">
        <%= f.submit(@small_generator.new_record? ? "Napravi novi agregat" : "Sačuvaj promene" , class: "btn btn-primary") %>
      </div>
    </div>
  </div>
<% end %>

app/views/small_generators/edit.html.erb
<h1>Izmene podataka: <%= @small_generator.model %></h1>

<%= render 'form' %>

<%= link_to 'Show', @small_generator, class: "btn btn-info" %>
<%= link_to 'Back', small_generators_path, class: "btn btn-inverse" %>

app/views/small_generators/index.html.erb
<h1>Mali prenosni agregati</h1>
<div class="row">
  <div class="span12">
    <p>
      <%= link_to '<i class="icon-file icon-white"></i> Novi agregat'.html_safe, new_small_generator_path, class: "btn btn-primary" %>
    </p>
  </div>
</div>
<table class="table generators_list">
  <tr>
    <th>Model</th>
    <th>Snaga (max)</th>
    <th>Snaga (cont)</th>
    <th>Motor</th>
    <th>Rezervoar</th>
    <th>Generator</th>
    <th>Panel</th>
    <th></th>
  </tr>

<% @small_generators.each do |small_generator| %>
  <tr>
    <td><%= link_to small_generator.model, small_generator %></td>
    <td><%= small_generator.kva_max %> kVA</td>
    <td><%= small_generator.kva_cont %> kVA</td>
    <td><%= small_generator.motor_proizvodjac %></td>
    <td><%= small_generator.motor_rezervoar %> l</td>
    <td><%= small_generator.generator_proizvodjac %></td>
    <td><%= small_generator.panel %></td>
    <td>
      <%= link_to '<i class="icon-download icon-white"></i> .pdf'.html_safe, small_generator_path(small_generator, format: :pdf), class: "btn btn-info btn-mini", target: "_blank" %>
      <%= link_to '<i class="icon-edit icon-white"></i> Edit'.html_safe, edit_small_generator_path(small_generator), class: "btn btn-warning btn-mini" %>
      <%= link_to '<i class="icon-trash icon-white"></i> Delete'.html_safe, small_generator, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-mini" %>
    </td>
  </tr>
<% end %>
</table>

app/views/small_generators/new.html.erb
<h1>Unos novog agregata</h1>

<%= render 'form' %>

<%= link_to 'Back', small_generators_path %>

app/views/small_generators/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="page-header">
  <h1><%= @small_generator.model %></h1>
</div>
<div class="row">
  <div class="span3">
    <strong>Stand by snaga</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.kva_max, separator: "," %> kVA
  </div>
  <div class="span3">
    <strong>Prime snaga</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.kva_cont, separator: "," %> kVA
  </div>
  <div class="span3">
    <strong>Stand by snaga</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.kw_max, separator: "," %> kW
  </div>
  <div class="span3">
    <strong>Prime snaga</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.kw_cont, separator: "," %> kW
  </div>
  <div class="span3">
    <strong>Napon</strong>
  </div>
  <div class="span3">
    <%= @small_generator.napon %> V
  </div>
  <div class="span3">
    <strong>Frekvencija</strong>
  </div>
  <div class="span3">
    <%= @small_generator.frekvencija %> Hz
  </div>
  <div class="span3">
    <strong>Start</strong>
  </div>
  <div class="span3">
    <%= @small_generator.start == "E" ? "Elektro start (ključ)" : "Ručni start (poteznica)" %>
  </div>
  <div class="span3">
    <strong>Nivo buke</strong>
  </div>
  <div class="span3">
    <%= @small_generator.nivo_buke %> dB
  </div>
  <div class="span3">
    <strong>Dimenzije (DxŠxV)</strong>
  </div>
  <div class="span3">
    <%= @small_generator.dimenzije %> mm
  </div>
  <div class="span3">
    <strong>Masa</strong>
  </div>
  <div class="span3">
    <%= @small_generator.masa %> kg
  </div>
  <div class="span3">
    <strong>Autonomija</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.autonomija, separator: "," %> h
  </div>
  <div class="span3">
    <strong>Tip panela</strong>
  </div>
  <div class="span3">
    <%= @small_generator.panel %>
  </div>
</div>
<div class="span12">
  <h3>Motor</h3>
</div>
<div class="row">
  <div class="span3">
    <strong>Proizvođač</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_proizvodjac %>
  </div>
  <div class="span3">
    <strong>Tip motora</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_tip %>
  </div>
  <div class="span3">
    <strong>Pogonsko gorivo</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_gorivo %>
  </div>
  <div class="span3">
    <strong>Vrsta hlađenja</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_hladjenje %>
  </div>
  <div class="span3">
    <strong>Snaga motora</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.motor_hp, separator: "," %> hp
  </div>
  <div class="span3">
    <strong>Zapremina motora</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_cm3 %> cm<sup>3</sup>
  </div>
  <div class="span3">
    <strong>Broj obrtaja u minuti</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_rpm %> rpm
  </div>
  <div class="span3">
    <strong>Broj cilindara</strong>
  </div>
  <div class="span3">
    <%= @small_generator.motor_cilindri %>
  </div>
  <div class="span3">
    <strong>Zapremina rezervoara</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.motor_rezervoar, separator: "," %> l
  </div>
  <div class="span3">
    <strong>Potrošnja na 75% opterećenja</strong>
  </div>
  <div class="span3">
    <%= number_with_delimiter @small_generator.motor_potrosnja_75, separator: "," %> l/h
  </div>
</div>
<div class="span12">
  <h3>Generator</h3>
</div>
<div class="row">
  <div class="span3">
    <strong>Proizvođač</strong>
  </div>
  <div class="span3">
    <%= @small_generator.generator_proizvodjac %>
  </div>
  <div class="span3">
    <strong>Tip generatora</strong>
  </div>
  <div class="span3">
    <%= @small_generator.generator_tip %>
  </div>
</div>
<% 3.times do %>
  <br>
<% end %>
<%= link_to '<i class="icon-arrow-left icon-white"></i> Back'.html_safe, small_generators_path, class: "btn btn-inverse" %>
<%= link_to '<i class="icon-edit icon-white"></i> Edit'.html_safe, edit_small_generator_path(@small_generator), class: "btn btn-warning" %>
<%= link_to '<i class="icon-download icon-white"></i> .pdf'.html_safe, small_generator_path(@small_generator, format: :pdf), target: "_blank", class: "btn btn-info" %>